/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWebhooksRouteImport } from './routes/_app/webhooks'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppStockRouteImport } from './routes/_app/stock'
import { Route as AppShopsRouteImport } from './routes/_app/shops'
import { Route as AppShippingRouteImport } from './routes/_app/shipping'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReviewsRouteImport } from './routes/_app/reviews'
import { Route as AppReturnsRouteImport } from './routes/_app/returns'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app/purchase-orders'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMovementsRouteImport } from './routes/_app/movements'
import { Route as AppMarketingRouteImport } from './routes/_app/marketing'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppLedgerRouteImport } from './routes/_app/ledger'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppDiscountsRouteImport } from './routes/_app/discounts'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppChannelsRouteImport } from './routes/_app/channels'
import { Route as AppAuditLogRouteImport } from './routes/_app/audit-log'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAccountingRouteImport } from './routes/_app/accounting'
import { Route as AppWebhooksIndexRouteImport } from './routes/_app/webhooks.index'
import { Route as AppStockIndexRouteImport } from './routes/_app/stock.index'
import { Route as AppShopsIndexRouteImport } from './routes/_app/shops.index'
import { Route as AppShippingIndexRouteImport } from './routes/_app/shipping.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppReviewsIndexRouteImport } from './routes/_app/reviews.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app/notifications.index'
import { Route as AppMarketingIndexRouteImport } from './routes/_app/marketing.index'
import { Route as AppDiscountsIndexRouteImport } from './routes/_app/discounts.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers.index'
import { Route as AppChannelsIndexRouteImport } from './routes/_app/channels.index'
import { Route as AppAuditLogIndexRouteImport } from './routes/_app/audit-log.index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/_app/analytics.index'
import { Route as AppAccountingIndexRouteImport } from './routes/_app/accounting.index'
import { Route as AppStockItemIdRouteImport } from './routes/_app/stock.$itemId'
import { Route as AppShopsIdRouteImport } from './routes/_app/shops.$id'
import { Route as AppSettingsWebhooksRouteImport } from './routes/_app/settings.webhooks'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings.users'
import { Route as AppSettingsTokensRouteImport } from './routes/_app/settings.tokens'
import { Route as AppProductsNewRouteImport } from './routes/_app/products.new'
import { Route as AppProductsIdRouteImport } from './routes/_app/products.$id'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders.$id'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers.$id'
import { Route as AppCmsPagesRouteImport } from './routes/_app/cms.pages'
import { Route as AppCmsMenusRouteImport } from './routes/_app/cms.menus'
import { Route as AppCmsMediaRouteImport } from './routes/_app/cms.media'
import { Route as AppCmsBlogRouteImport } from './routes/_app/cms.blog'
import { Route as AppChannelsMatrixRouteImport } from './routes/_app/channels.matrix'
import { Route as AppAccountingKoppelingenRouteImport } from './routes/_app/accounting.koppelingen'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsRoute = AppShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AppRoute,
} as any)
const AppShippingRoute = AppShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscountsRoute = AppDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingRoute = AppAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebhooksRoute,
} as any)
const AppStockIndexRoute = AppStockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStockRoute,
} as any)
const AppShopsIndexRoute = AppShopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShopsRoute,
} as any)
const AppShippingIndexRoute = AppShippingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShippingRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReviewsIndexRoute = AppReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReviewsRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotificationsRoute,
} as any)
const AppMarketingIndexRoute = AppMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppDiscountsIndexRoute = AppDiscountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDiscountsRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppChannelsIndexRoute = AppChannelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChannelsRoute,
} as any)
const AppAuditLogIndexRoute = AppAuditLogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditLogRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAnalyticsRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountingRoute,
} as any)
const AppStockItemIdRoute = AppStockItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppStockRoute,
} as any)
const AppShopsIdRoute = AppShopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppShopsRoute,
} as any)
const AppSettingsWebhooksRoute = AppSettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTokensRoute = AppSettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCmsPagesRoute = AppCmsPagesRouteImport.update({
  id: '/cms/pages',
  path: '/cms/pages',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsMenusRoute = AppCmsMenusRouteImport.update({
  id: '/cms/menus',
  path: '/cms/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsMediaRoute = AppCmsMediaRouteImport.update({
  id: '/cms/media',
  path: '/cms/media',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsBlogRoute = AppCmsBlogRouteImport.update({
  id: '/cms/blog',
  path: '/cms/blog',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsMatrixRoute = AppChannelsMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => AppChannelsRoute,
} as any)
const AppAccountingKoppelingenRoute =
  AppAccountingKoppelingenRouteImport.update({
    id: '/koppelingen',
    path: '/koppelingen',
    getParentRoute: () => AppAccountingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/accounting': typeof AppAccountingRouteWithChildren
  '/analytics': typeof AppAnalyticsRouteWithChildren
  '/audit-log': typeof AppAuditLogRouteWithChildren
  '/channels': typeof AppChannelsRouteWithChildren
  '/customers': typeof AppCustomersRouteWithChildren
  '/discounts': typeof AppDiscountsRouteWithChildren
  '/finance': typeof AppFinanceRoute
  '/ledger': typeof AppLedgerRoute
  '/locations': typeof AppLocationsRoute
  '/marketing': typeof AppMarketingRouteWithChildren
  '/movements': typeof AppMovementsRoute
  '/notifications': typeof AppNotificationsRouteWithChildren
  '/orders': typeof AppOrdersRouteWithChildren
  '/products': typeof AppProductsRouteWithChildren
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/returns': typeof AppReturnsRoute
  '/reviews': typeof AppReviewsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/shipping': typeof AppShippingRouteWithChildren
  '/shops': typeof AppShopsRouteWithChildren
  '/stock': typeof AppStockRouteWithChildren
  '/suppliers': typeof AppSuppliersRoute
  '/webhooks': typeof AppWebhooksRouteWithChildren
  '/accounting/koppelingen': typeof AppAccountingKoppelingenRoute
  '/channels/matrix': typeof AppChannelsMatrixRoute
  '/cms/blog': typeof AppCmsBlogRoute
  '/cms/media': typeof AppCmsMediaRoute
  '/cms/menus': typeof AppCmsMenusRoute
  '/cms/pages': typeof AppCmsPagesRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/shops/$id': typeof AppShopsIdRoute
  '/stock/$itemId': typeof AppStockItemIdRoute
  '/accounting/': typeof AppAccountingIndexRoute
  '/analytics/': typeof AppAnalyticsIndexRoute
  '/audit-log/': typeof AppAuditLogIndexRoute
  '/channels/': typeof AppChannelsIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/discounts/': typeof AppDiscountsIndexRoute
  '/marketing/': typeof AppMarketingIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/reviews/': typeof AppReviewsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/shipping/': typeof AppShippingIndexRoute
  '/shops/': typeof AppShopsIndexRoute
  '/stock/': typeof AppStockIndexRoute
  '/webhooks/': typeof AppWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/finance': typeof AppFinanceRoute
  '/ledger': typeof AppLedgerRoute
  '/locations': typeof AppLocationsRoute
  '/movements': typeof AppMovementsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/returns': typeof AppReturnsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/': typeof AppIndexRoute
  '/accounting/koppelingen': typeof AppAccountingKoppelingenRoute
  '/channels/matrix': typeof AppChannelsMatrixRoute
  '/cms/blog': typeof AppCmsBlogRoute
  '/cms/media': typeof AppCmsMediaRoute
  '/cms/menus': typeof AppCmsMenusRoute
  '/cms/pages': typeof AppCmsPagesRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/settings/tokens': typeof AppSettingsTokensRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/shops/$id': typeof AppShopsIdRoute
  '/stock/$itemId': typeof AppStockItemIdRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/audit-log': typeof AppAuditLogIndexRoute
  '/channels': typeof AppChannelsIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/discounts': typeof AppDiscountsIndexRoute
  '/marketing': typeof AppMarketingIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/reviews': typeof AppReviewsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/shipping': typeof AppShippingIndexRoute
  '/shops': typeof AppShopsIndexRoute
  '/stock': typeof AppStockIndexRoute
  '/webhooks': typeof AppWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/_app/accounting': typeof AppAccountingRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRouteWithChildren
  '/_app/audit-log': typeof AppAuditLogRouteWithChildren
  '/_app/channels': typeof AppChannelsRouteWithChildren
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/discounts': typeof AppDiscountsRouteWithChildren
  '/_app/finance': typeof AppFinanceRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/marketing': typeof AppMarketingRouteWithChildren
  '/_app/movements': typeof AppMovementsRoute
  '/_app/notifications': typeof AppNotificationsRouteWithChildren
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/returns': typeof AppReturnsRoute
  '/_app/reviews': typeof AppReviewsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/shipping': typeof AppShippingRouteWithChildren
  '/_app/shops': typeof AppShopsRouteWithChildren
  '/_app/stock': typeof AppStockRouteWithChildren
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/webhooks': typeof AppWebhooksRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/accounting/koppelingen': typeof AppAccountingKoppelingenRoute
  '/_app/channels/matrix': typeof AppChannelsMatrixRoute
  '/_app/cms/blog': typeof AppCmsBlogRoute
  '/_app/cms/media': typeof AppCmsMediaRoute
  '/_app/cms/menus': typeof AppCmsMenusRoute
  '/_app/cms/pages': typeof AppCmsPagesRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/settings/tokens': typeof AppSettingsTokensRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/settings/webhooks': typeof AppSettingsWebhooksRoute
  '/_app/shops/$id': typeof AppShopsIdRoute
  '/_app/stock/$itemId': typeof AppStockItemIdRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/analytics/': typeof AppAnalyticsIndexRoute
  '/_app/audit-log/': typeof AppAuditLogIndexRoute
  '/_app/channels/': typeof AppChannelsIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/discounts/': typeof AppDiscountsIndexRoute
  '/_app/marketing/': typeof AppMarketingIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/reviews/': typeof AppReviewsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/shipping/': typeof AppShippingIndexRoute
  '/_app/shops/': typeof AppShopsIndexRoute
  '/_app/stock/': typeof AppStockIndexRoute
  '/_app/webhooks/': typeof AppWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launch'
    | '/login'
    | '/accounting'
    | '/analytics'
    | '/audit-log'
    | '/channels'
    | '/customers'
    | '/discounts'
    | '/finance'
    | '/ledger'
    | '/locations'
    | '/marketing'
    | '/movements'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/purchase-orders'
    | '/returns'
    | '/reviews'
    | '/settings'
    | '/shipping'
    | '/shops'
    | '/stock'
    | '/suppliers'
    | '/webhooks'
    | '/accounting/koppelingen'
    | '/channels/matrix'
    | '/cms/blog'
    | '/cms/media'
    | '/cms/menus'
    | '/cms/pages'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/settings/tokens'
    | '/settings/users'
    | '/settings/webhooks'
    | '/shops/$id'
    | '/stock/$itemId'
    | '/accounting/'
    | '/analytics/'
    | '/audit-log/'
    | '/channels/'
    | '/customers/'
    | '/discounts/'
    | '/marketing/'
    | '/notifications/'
    | '/orders/'
    | '/products/'
    | '/reviews/'
    | '/settings/'
    | '/shipping/'
    | '/shops/'
    | '/stock/'
    | '/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/launch'
    | '/login'
    | '/finance'
    | '/ledger'
    | '/locations'
    | '/movements'
    | '/purchase-orders'
    | '/returns'
    | '/suppliers'
    | '/'
    | '/accounting/koppelingen'
    | '/channels/matrix'
    | '/cms/blog'
    | '/cms/media'
    | '/cms/menus'
    | '/cms/pages'
    | '/customers/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/products/new'
    | '/settings/tokens'
    | '/settings/users'
    | '/settings/webhooks'
    | '/shops/$id'
    | '/stock/$itemId'
    | '/accounting'
    | '/analytics'
    | '/audit-log'
    | '/channels'
    | '/customers'
    | '/discounts'
    | '/marketing'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/reviews'
    | '/settings'
    | '/shipping'
    | '/shops'
    | '/stock'
    | '/webhooks'
  id:
    | '__root__'
    | '/_app'
    | '/launch'
    | '/login'
    | '/_app/accounting'
    | '/_app/analytics'
    | '/_app/audit-log'
    | '/_app/channels'
    | '/_app/customers'
    | '/_app/discounts'
    | '/_app/finance'
    | '/_app/ledger'
    | '/_app/locations'
    | '/_app/marketing'
    | '/_app/movements'
    | '/_app/notifications'
    | '/_app/orders'
    | '/_app/products'
    | '/_app/purchase-orders'
    | '/_app/returns'
    | '/_app/reviews'
    | '/_app/settings'
    | '/_app/shipping'
    | '/_app/shops'
    | '/_app/stock'
    | '/_app/suppliers'
    | '/_app/webhooks'
    | '/_app/'
    | '/_app/accounting/koppelingen'
    | '/_app/channels/matrix'
    | '/_app/cms/blog'
    | '/_app/cms/media'
    | '/_app/cms/menus'
    | '/_app/cms/pages'
    | '/_app/customers/$id'
    | '/_app/orders/$id'
    | '/_app/products/$id'
    | '/_app/products/new'
    | '/_app/settings/tokens'
    | '/_app/settings/users'
    | '/_app/settings/webhooks'
    | '/_app/shops/$id'
    | '/_app/stock/$itemId'
    | '/_app/accounting/'
    | '/_app/analytics/'
    | '/_app/audit-log/'
    | '/_app/channels/'
    | '/_app/customers/'
    | '/_app/discounts/'
    | '/_app/marketing/'
    | '/_app/notifications/'
    | '/_app/orders/'
    | '/_app/products/'
    | '/_app/reviews/'
    | '/_app/settings/'
    | '/_app/shipping/'
    | '/_app/shops/'
    | '/_app/stock/'
    | '/_app/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks': {
      id: '/_app/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shops': {
      id: '/_app/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof AppShopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shipping': {
      id: '/_app/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AppShippingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns': {
      id: '/_app/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements': {
      id: '/_app/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discounts': {
      id: '/_app/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AppDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels': {
      id: '/_app/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting': {
      id: '/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AppAccountingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks/': {
      id: '/_app/webhooks/'
      path: '/'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppWebhooksRoute
    }
    '/_app/stock/': {
      id: '/_app/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof AppStockIndexRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/shops/': {
      id: '/_app/shops/'
      path: '/'
      fullPath: '/shops/'
      preLoaderRoute: typeof AppShopsIndexRouteImport
      parentRoute: typeof AppShopsRoute
    }
    '/_app/shipping/': {
      id: '/_app/shipping/'
      path: '/'
      fullPath: '/shipping/'
      preLoaderRoute: typeof AppShippingIndexRouteImport
      parentRoute: typeof AppShippingRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/reviews/': {
      id: '/_app/reviews/'
      path: '/'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AppReviewsIndexRouteImport
      parentRoute: typeof AppReviewsRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppNotificationsRoute
    }
    '/_app/marketing/': {
      id: '/_app/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AppMarketingIndexRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/discounts/': {
      id: '/_app/discounts/'
      path: '/'
      fullPath: '/discounts/'
      preLoaderRoute: typeof AppDiscountsIndexRouteImport
      parentRoute: typeof AppDiscountsRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/channels/': {
      id: '/_app/channels/'
      path: '/'
      fullPath: '/channels/'
      preLoaderRoute: typeof AppChannelsIndexRouteImport
      parentRoute: typeof AppChannelsRoute
    }
    '/_app/audit-log/': {
      id: '/_app/audit-log/'
      path: '/'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AppAuditLogIndexRouteImport
      parentRoute: typeof AppAuditLogRoute
    }
    '/_app/analytics/': {
      id: '/_app/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppAnalyticsRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppAccountingRoute
    }
    '/_app/stock/$itemId': {
      id: '/_app/stock/$itemId'
      path: '/$itemId'
      fullPath: '/stock/$itemId'
      preLoaderRoute: typeof AppStockItemIdRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/shops/$id': {
      id: '/_app/shops/$id'
      path: '/$id'
      fullPath: '/shops/$id'
      preLoaderRoute: typeof AppShopsIdRouteImport
      parentRoute: typeof AppShopsRoute
    }
    '/_app/settings/webhooks': {
      id: '/_app/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AppSettingsWebhooksRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/tokens': {
      id: '/_app/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AppSettingsTokensRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/cms/pages': {
      id: '/_app/cms/pages'
      path: '/cms/pages'
      fullPath: '/cms/pages'
      preLoaderRoute: typeof AppCmsPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cms/menus': {
      id: '/_app/cms/menus'
      path: '/cms/menus'
      fullPath: '/cms/menus'
      preLoaderRoute: typeof AppCmsMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cms/media': {
      id: '/_app/cms/media'
      path: '/cms/media'
      fullPath: '/cms/media'
      preLoaderRoute: typeof AppCmsMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cms/blog': {
      id: '/_app/cms/blog'
      path: '/cms/blog'
      fullPath: '/cms/blog'
      preLoaderRoute: typeof AppCmsBlogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/matrix': {
      id: '/_app/channels/matrix'
      path: '/matrix'
      fullPath: '/channels/matrix'
      preLoaderRoute: typeof AppChannelsMatrixRouteImport
      parentRoute: typeof AppChannelsRoute
    }
    '/_app/accounting/koppelingen': {
      id: '/_app/accounting/koppelingen'
      path: '/koppelingen'
      fullPath: '/accounting/koppelingen'
      preLoaderRoute: typeof AppAccountingKoppelingenRouteImport
      parentRoute: typeof AppAccountingRoute
    }
  }
}

interface AppAccountingRouteChildren {
  AppAccountingKoppelingenRoute: typeof AppAccountingKoppelingenRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
}

const AppAccountingRouteChildren: AppAccountingRouteChildren = {
  AppAccountingKoppelingenRoute: AppAccountingKoppelingenRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
}

const AppAccountingRouteWithChildren = AppAccountingRoute._addFileChildren(
  AppAccountingRouteChildren,
)

interface AppAnalyticsRouteChildren {
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
}

const AppAnalyticsRouteChildren: AppAnalyticsRouteChildren = {
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
}

const AppAnalyticsRouteWithChildren = AppAnalyticsRoute._addFileChildren(
  AppAnalyticsRouteChildren,
)

interface AppAuditLogRouteChildren {
  AppAuditLogIndexRoute: typeof AppAuditLogIndexRoute
}

const AppAuditLogRouteChildren: AppAuditLogRouteChildren = {
  AppAuditLogIndexRoute: AppAuditLogIndexRoute,
}

const AppAuditLogRouteWithChildren = AppAuditLogRoute._addFileChildren(
  AppAuditLogRouteChildren,
)

interface AppChannelsRouteChildren {
  AppChannelsMatrixRoute: typeof AppChannelsMatrixRoute
  AppChannelsIndexRoute: typeof AppChannelsIndexRoute
}

const AppChannelsRouteChildren: AppChannelsRouteChildren = {
  AppChannelsMatrixRoute: AppChannelsMatrixRoute,
  AppChannelsIndexRoute: AppChannelsIndexRoute,
}

const AppChannelsRouteWithChildren = AppChannelsRoute._addFileChildren(
  AppChannelsRouteChildren,
)

interface AppCustomersRouteChildren {
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppDiscountsRouteChildren {
  AppDiscountsIndexRoute: typeof AppDiscountsIndexRoute
}

const AppDiscountsRouteChildren: AppDiscountsRouteChildren = {
  AppDiscountsIndexRoute: AppDiscountsIndexRoute,
}

const AppDiscountsRouteWithChildren = AppDiscountsRoute._addFileChildren(
  AppDiscountsRouteChildren,
)

interface AppMarketingRouteChildren {
  AppMarketingIndexRoute: typeof AppMarketingIndexRoute
}

const AppMarketingRouteChildren: AppMarketingRouteChildren = {
  AppMarketingIndexRoute: AppMarketingIndexRoute,
}

const AppMarketingRouteWithChildren = AppMarketingRoute._addFileChildren(
  AppMarketingRouteChildren,
)

interface AppNotificationsRouteChildren {
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
}

const AppNotificationsRouteChildren: AppNotificationsRouteChildren = {
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
}

const AppNotificationsRouteWithChildren =
  AppNotificationsRoute._addFileChildren(AppNotificationsRouteChildren)

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppReviewsRouteChildren {
  AppReviewsIndexRoute: typeof AppReviewsIndexRoute
}

const AppReviewsRouteChildren: AppReviewsRouteChildren = {
  AppReviewsIndexRoute: AppReviewsIndexRoute,
}

const AppReviewsRouteWithChildren = AppReviewsRoute._addFileChildren(
  AppReviewsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsTokensRoute: typeof AppSettingsTokensRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSettingsWebhooksRoute: typeof AppSettingsWebhooksRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsTokensRoute: AppSettingsTokensRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSettingsWebhooksRoute: AppSettingsWebhooksRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppShippingRouteChildren {
  AppShippingIndexRoute: typeof AppShippingIndexRoute
}

const AppShippingRouteChildren: AppShippingRouteChildren = {
  AppShippingIndexRoute: AppShippingIndexRoute,
}

const AppShippingRouteWithChildren = AppShippingRoute._addFileChildren(
  AppShippingRouteChildren,
)

interface AppShopsRouteChildren {
  AppShopsIdRoute: typeof AppShopsIdRoute
  AppShopsIndexRoute: typeof AppShopsIndexRoute
}

const AppShopsRouteChildren: AppShopsRouteChildren = {
  AppShopsIdRoute: AppShopsIdRoute,
  AppShopsIndexRoute: AppShopsIndexRoute,
}

const AppShopsRouteWithChildren = AppShopsRoute._addFileChildren(
  AppShopsRouteChildren,
)

interface AppStockRouteChildren {
  AppStockItemIdRoute: typeof AppStockItemIdRoute
  AppStockIndexRoute: typeof AppStockIndexRoute
}

const AppStockRouteChildren: AppStockRouteChildren = {
  AppStockItemIdRoute: AppStockItemIdRoute,
  AppStockIndexRoute: AppStockIndexRoute,
}

const AppStockRouteWithChildren = AppStockRoute._addFileChildren(
  AppStockRouteChildren,
)

interface AppWebhooksRouteChildren {
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
}

const AppWebhooksRouteChildren: AppWebhooksRouteChildren = {
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
}

const AppWebhooksRouteWithChildren = AppWebhooksRoute._addFileChildren(
  AppWebhooksRouteChildren,
)

interface AppRouteChildren {
  AppAccountingRoute: typeof AppAccountingRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRouteWithChildren
  AppAuditLogRoute: typeof AppAuditLogRouteWithChildren
  AppChannelsRoute: typeof AppChannelsRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDiscountsRoute: typeof AppDiscountsRouteWithChildren
  AppFinanceRoute: typeof AppFinanceRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMarketingRoute: typeof AppMarketingRouteWithChildren
  AppMovementsRoute: typeof AppMovementsRoute
  AppNotificationsRoute: typeof AppNotificationsRouteWithChildren
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppReviewsRoute: typeof AppReviewsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppShippingRoute: typeof AppShippingRouteWithChildren
  AppShopsRoute: typeof AppShopsRouteWithChildren
  AppStockRoute: typeof AppStockRouteWithChildren
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppWebhooksRoute: typeof AppWebhooksRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCmsBlogRoute: typeof AppCmsBlogRoute
  AppCmsMediaRoute: typeof AppCmsMediaRoute
  AppCmsMenusRoute: typeof AppCmsMenusRoute
  AppCmsPagesRoute: typeof AppCmsPagesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountingRoute: AppAccountingRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRouteWithChildren,
  AppAuditLogRoute: AppAuditLogRouteWithChildren,
  AppChannelsRoute: AppChannelsRouteWithChildren,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDiscountsRoute: AppDiscountsRouteWithChildren,
  AppFinanceRoute: AppFinanceRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMarketingRoute: AppMarketingRouteWithChildren,
  AppMovementsRoute: AppMovementsRoute,
  AppNotificationsRoute: AppNotificationsRouteWithChildren,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppReviewsRoute: AppReviewsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppShippingRoute: AppShippingRouteWithChildren,
  AppShopsRoute: AppShopsRouteWithChildren,
  AppStockRoute: AppStockRouteWithChildren,
  AppSuppliersRoute: AppSuppliersRoute,
  AppWebhooksRoute: AppWebhooksRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCmsBlogRoute: AppCmsBlogRoute,
  AppCmsMediaRoute: AppCmsMediaRoute,
  AppCmsMenusRoute: AppCmsMenusRoute,
  AppCmsPagesRoute: AppCmsPagesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
