-- ============================================================
-- Initial migration — Fase 1 foundation
-- Generated by Atlas (handmatig conform Drizzle-conventies).
--
-- LET OP: Bij `pnpm db:generate` zal drizzle-kit checken of dit overeenkomt
-- met `src/db/schema/`. Als drift ontstaat, herregenereer:
--   1. Drop deze file (incl. drizzle/meta/_journal.json + 0000_snapshot.json)
--   2. Run `pnpm db:generate`
--
-- Inclusief: pgcrypto-extensie + alle V1-foundation-tabellen.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── auth: users ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "email" text NOT NULL UNIQUE,
  "password_hash" text NOT NULL,
  "role" text DEFAULT 'admin' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── auth: sessions ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "sessions" (
  "id" text PRIMARY KEY NOT NULL,
  "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "expires_at" timestamp with time zone NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── auth: api_tokens ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "api_tokens" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "token_hash" text NOT NULL UNIQUE,
  "scope" text NOT NULL,
  "label" text NOT NULL,
  "last_used_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── locations ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "locations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "code" text NOT NULL UNIQUE,
  "name" text NOT NULL,
  "type" text DEFAULT 'warehouse' NOT NULL,
  "priority" integer DEFAULT 100 NOT NULL,
  "address" jsonb,
  "active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── catalog: products ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS "products" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "title" text NOT NULL,
  "description_html" text,
  "vendor" text,
  "product_type" text,
  "status" text DEFAULT 'draft' NOT NULL,
  "tags" text[] DEFAULT '{}' NOT NULL,
  "published_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── catalog: product_options ────────────────────────────────
CREATE TABLE IF NOT EXISTS "product_options" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "name" text NOT NULL,
  "position" integer DEFAULT 0 NOT NULL
);

-- ─── catalog: product_option_values ──────────────────────────
CREATE TABLE IF NOT EXISTS "product_option_values" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "option_id" uuid NOT NULL REFERENCES "product_options"("id") ON DELETE CASCADE,
  "value" text NOT NULL,
  "position" integer DEFAULT 0 NOT NULL
);

-- ─── catalog: product_images ─────────────────────────────────
CREATE TABLE IF NOT EXISTS "product_images" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "url" text NOT NULL,
  "alt" text,
  "position" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── catalog: variants ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS "variants" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "sku" text NOT NULL UNIQUE,
  "price" numeric(12, 4) NOT NULL,
  "compare_at_price" numeric(12, 4),
  "cost_price" numeric(12, 4),
  "weight_g" integer,
  "length_mm" integer,
  "width_mm" integer,
  "height_mm" integer,
  "barcode" text,
  "selected_options" jsonb DEFAULT '{}' NOT NULL,
  "position" integer DEFAULT 0 NOT NULL,
  "taxable" boolean DEFAULT true NOT NULL,
  "tax_class" text DEFAULT 'standard' NOT NULL,
  "active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── inventory: items ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "inventory_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "variant_id" uuid NOT NULL UNIQUE REFERENCES "variants"("id") ON DELETE CASCADE,
  "sku" text NOT NULL UNIQUE,
  "tracked" boolean DEFAULT true NOT NULL,
  "requires_shipping" boolean DEFAULT true NOT NULL,
  "gtin" text,
  "gtin_is_gs1_registered" boolean DEFAULT false NOT NULL,
  "hs_code" text,
  "country_of_origin" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS "inventory_items_gtin_idx" ON "inventory_items" ("gtin");

-- ─── inventory: levels ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS "inventory_levels" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "item_id" uuid NOT NULL REFERENCES "inventory_items"("id") ON DELETE CASCADE,
  "location_id" uuid NOT NULL REFERENCES "locations"("id"),
  "on_hand" integer DEFAULT 0 NOT NULL,
  "available" integer DEFAULT 0 NOT NULL,
  "committed" integer DEFAULT 0 NOT NULL,
  "incoming" integer DEFAULT 0 NOT NULL,
  "min_stock" integer,
  "reorder_point" integer,
  "reorder_qty" integer,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "inventory_levels_item_location_unique" UNIQUE ("item_id", "location_id")
);

-- ─── inventory: movements ────────────────────────────────────
CREATE TABLE IF NOT EXISTS "inventory_movements" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "item_id" uuid NOT NULL REFERENCES "inventory_items"("id") ON DELETE CASCADE,
  "location_id" uuid NOT NULL REFERENCES "locations"("id"),
  "delta" integer NOT NULL,
  "reason" text NOT NULL,
  "ref_type" text,
  "ref_id" uuid,
  "actor_id" uuid,
  "note" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS "inventory_movements_item_idx"
  ON "inventory_movements" ("item_id", "created_at");

-- ─── inventory: reservations ─────────────────────────────────
CREATE TABLE IF NOT EXISTS "inventory_reservations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "item_id" uuid NOT NULL REFERENCES "inventory_items"("id") ON DELETE CASCADE,
  "location_id" uuid NOT NULL REFERENCES "locations"("id"),
  "quantity" integer NOT NULL,
  "reason" text NOT NULL,
  "ref_type" text NOT NULL,
  "ref_id" uuid NOT NULL,
  "expires_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "inventory_reservations_qty_positive" CHECK ("quantity" > 0)
);
CREATE INDEX IF NOT EXISTS "inventory_reservations_expires_idx"
  ON "inventory_reservations" ("expires_at");

-- ─── cross-cutting: audit_log ────────────────────────────────
CREATE TABLE IF NOT EXISTS "audit_log" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "actor_type" text NOT NULL,
  "actor_id" text,
  "action" text NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" uuid,
  "before" jsonb,
  "after" jsonb,
  "ip" text,
  "ts" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS "audit_log_entity_idx"
  ON "audit_log" ("entity_type", "entity_id", "ts");

-- ─── cross-cutting: idempotency_keys ─────────────────────────
CREATE TABLE IF NOT EXISTS "idempotency_keys" (
  "key" text PRIMARY KEY NOT NULL,
  "scope" text NOT NULL,
  "response_status" integer NOT NULL,
  "response_body" jsonb,
  "expires_at" timestamp with time zone NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ============================================================
-- updated_at-trigger helper (gebruikt door schema's met updated_at)
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON "products"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER variants_updated_at
  BEFORE UPDATE ON "variants"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER inventory_levels_updated_at
  BEFORE UPDATE ON "inventory_levels"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
