-- ============================================================
-- Migration 0001 — Fase 2: multi-shop + CMS + commerce
--                   + purchasing + financieel + channels
-- Generated by Atlas (handmatig conform Drizzle-conventies).
--
-- LET OP: drizzle-kit 0.28.1 kan de ESM `.js`-imports in schema/index.ts niet
-- via zijn CJS-loader resolven, dus `db:generate` faalt (zoals bij 0000).
-- Daarom is deze migratie handgeschreven — PUUR ADDITIEF. 0000 + bestaande
-- tabellen worden NOOIT aangeraakt. `set_updated_at()` bestaat al uit 0000.
--
-- 30 nieuwe tabellen. FK-volgorde respecteert dependencies.
-- ============================================================

-- ════════════════════════════════════════════════════════════
-- 1. Multi-shop
-- ════════════════════════════════════════════════════════════

-- ─── shops ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "shops" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "slug" text NOT NULL UNIQUE,
  "name" text NOT NULL,
  "domain" text UNIQUE,
  "locale" text DEFAULT 'nl-NL' NOT NULL,
  "currency" text DEFAULT 'EUR' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "branding" jsonb DEFAULT '{}' NOT NULL,
  "vat_config" jsonb DEFAULT '{}' NOT NULL,
  "default_location_id" uuid REFERENCES "locations"("id") ON DELETE SET NULL,
  "support_email" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── shop_products ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "shop_products" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "product_id" uuid NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "published" boolean DEFAULT false NOT NULL,
  "price_override" numeric(12, 4),
  "position" integer DEFAULT 0 NOT NULL,
  "published_at" timestamp with time zone,
  CONSTRAINT "shop_products_shop_product_unique" UNIQUE ("shop_id", "product_id")
);

-- ════════════════════════════════════════════════════════════
-- 2. CMS
-- ════════════════════════════════════════════════════════════

-- ─── cms_pages ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "cms_pages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "slug" text NOT NULL,
  "title" text NOT NULL,
  "status" text DEFAULT 'draft' NOT NULL,
  "template" text DEFAULT 'default' NOT NULL,
  "blocks" jsonb DEFAULT '[]' NOT NULL,
  "seo" jsonb DEFAULT '{}' NOT NULL,
  "published_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "cms_pages_shop_slug_unique" UNIQUE ("shop_id", "slug")
);

-- ─── cms_blocks ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "cms_blocks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "key" text NOT NULL,
  "type" text NOT NULL,
  "content" jsonb DEFAULT '{}' NOT NULL,
  "active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "cms_blocks_shop_key_unique" UNIQUE ("shop_id", "key")
);

-- ─── cms_menus ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "cms_menus" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "location" text NOT NULL,
  "name" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "cms_menus_shop_location_name_unique" UNIQUE ("shop_id", "location", "name")
);

-- ─── cms_menu_items (self-FK parent_id) ──────────────────────
CREATE TABLE IF NOT EXISTS "cms_menu_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "menu_id" uuid NOT NULL REFERENCES "cms_menus"("id") ON DELETE CASCADE,
  "parent_id" uuid REFERENCES "cms_menu_items"("id") ON DELETE SET NULL,
  "label" text NOT NULL,
  "url" text NOT NULL,
  "position" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── blog_posts ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "blog_posts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "slug" text NOT NULL,
  "title" text NOT NULL,
  "excerpt" text,
  "body_html" text,
  "cover_image" text,
  "status" text DEFAULT 'draft' NOT NULL,
  "author" text,
  "tags" text[] DEFAULT '{}' NOT NULL,
  "seo" jsonb DEFAULT '{}' NOT NULL,
  "published_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "blog_posts_shop_slug_unique" UNIQUE ("shop_id", "slug")
);

-- ─── cms_media (shop_id NULL = globaal) ──────────────────────
CREATE TABLE IF NOT EXISTS "cms_media" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid REFERENCES "shops"("id") ON DELETE CASCADE,
  "url" text NOT NULL,
  "filename" text NOT NULL,
  "mime" text,
  "size_bytes" integer,
  "width" integer,
  "height" integer,
  "alt" text,
  "folder" text DEFAULT 'uploads' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── cms_redirects ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "cms_redirects" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "from_path" text NOT NULL,
  "to_path" text NOT NULL,
  "status_code" integer DEFAULT 301 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "cms_redirects_shop_from_path_unique" UNIQUE ("shop_id", "from_path")
);

-- ════════════════════════════════════════════════════════════
-- 3. Commerce
-- ════════════════════════════════════════════════════════════

-- ─── customers ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "customers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "email" text NOT NULL,
  "first_name" text,
  "last_name" text,
  "phone" text,
  "company" text,
  "vat_number" text,
  "accepts_marketing" boolean DEFAULT false NOT NULL,
  "tags" text[] DEFAULT '{}' NOT NULL,
  "notes" text,
  "orders_count" integer DEFAULT 0 NOT NULL,
  "total_spent" numeric(12, 4) DEFAULT '0' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "customers_shop_email_unique" UNIQUE ("shop_id", "email")
);

-- ─── customer_addresses ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS "customer_addresses" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "customer_id" uuid NOT NULL REFERENCES "customers"("id") ON DELETE CASCADE,
  "type" text NOT NULL,
  "is_default" boolean DEFAULT false NOT NULL,
  "name" text,
  "line1" text,
  "line2" text,
  "postcode" text,
  "city" text,
  "province" text,
  "country" text,
  "phone" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── orders ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "orders" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE RESTRICT,
  "order_number" text NOT NULL,
  "customer_id" uuid REFERENCES "customers"("id") ON DELETE SET NULL,
  "email" text,
  "channel" text DEFAULT 'web' NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "financial_status" text DEFAULT 'pending' NOT NULL,
  "fulfillment_status" text DEFAULT 'unfulfilled' NOT NULL,
  "currency" text DEFAULT 'EUR' NOT NULL,
  "subtotal" numeric(12, 4),
  "discount_total" numeric(12, 4) DEFAULT '0' NOT NULL,
  "shipping_total" numeric(12, 4) DEFAULT '0' NOT NULL,
  "tax_total" numeric(12, 4) DEFAULT '0' NOT NULL,
  "grand_total" numeric(12, 4),
  "billing_address" jsonb,
  "shipping_address" jsonb,
  "note" text,
  "placed_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "orders_shop_order_number_unique" UNIQUE ("shop_id", "order_number")
);
CREATE INDEX IF NOT EXISTS "orders_shop_status_created_idx"
  ON "orders" ("shop_id", "status", "created_at");

-- ─── order_items ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "order_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "order_id" uuid NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "variant_id" uuid REFERENCES "variants"("id") ON DELETE SET NULL,
  "sku" text,
  "title" text,
  "quantity" integer NOT NULL,
  "unit_price" numeric(12, 4),
  "tax_rate" numeric(5, 2) DEFAULT '21' NOT NULL,
  "tax_amount" numeric(12, 4) DEFAULT '0' NOT NULL,
  "cost_price" numeric(12, 4),
  "line_total" numeric(12, 4)
);

-- ─── order_payments ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "order_payments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "order_id" uuid NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "provider" text,
  "amount" numeric(12, 4),
  "status" text DEFAULT 'pending' NOT NULL,
  "reference" text,
  "paid_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── order_fulfillments ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS "order_fulfillments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "order_id" uuid NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "location_id" uuid REFERENCES "locations"("id") ON DELETE SET NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "carrier" text,
  "tracking_code" text,
  "tracking_url" text,
  "shipped_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── carts ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "carts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "token" text NOT NULL UNIQUE,
  "customer_id" uuid REFERENCES "customers"("id") ON DELETE SET NULL,
  "currency" text DEFAULT 'EUR' NOT NULL,
  "expires_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── cart_items ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "cart_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "cart_id" uuid NOT NULL REFERENCES "carts"("id") ON DELETE CASCADE,
  "variant_id" uuid NOT NULL REFERENCES "variants"("id") ON DELETE CASCADE,
  "quantity" integer NOT NULL,
  "unit_price" numeric(12, 4),
  CONSTRAINT "cart_items_cart_variant_unique" UNIQUE ("cart_id", "variant_id")
);

-- ─── returns ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "returns" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE CASCADE,
  "order_id" uuid REFERENCES "orders"("id") ON DELETE SET NULL,
  "status" text DEFAULT 'requested' NOT NULL,
  "reason" text,
  "refund_amount" numeric(12, 4) DEFAULT '0' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── return_items ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "return_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "return_id" uuid NOT NULL REFERENCES "returns"("id") ON DELETE CASCADE,
  "order_item_id" uuid REFERENCES "order_items"("id") ON DELETE SET NULL,
  "quantity" integer,
  "restock" boolean DEFAULT true NOT NULL
);

-- ════════════════════════════════════════════════════════════
-- 4. Purchasing
-- ════════════════════════════════════════════════════════════

-- ─── suppliers ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "suppliers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "email" text,
  "phone" text,
  "address" jsonb,
  "lead_time_days" integer DEFAULT 7 NOT NULL,
  "currency" text DEFAULT 'EUR' NOT NULL,
  "notes" text,
  "active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── purchase_orders ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "purchase_orders" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "supplier_id" uuid NOT NULL REFERENCES "suppliers"("id") ON DELETE RESTRICT,
  "location_id" uuid REFERENCES "locations"("id") ON DELETE SET NULL,
  "reference" text,
  "status" text DEFAULT 'draft' NOT NULL,
  "currency" text DEFAULT 'EUR' NOT NULL,
  "subtotal" numeric(12, 4) DEFAULT '0' NOT NULL,
  "tax_total" numeric(12, 4) DEFAULT '0' NOT NULL,
  "total" numeric(12, 4) DEFAULT '0' NOT NULL,
  "expected_at" timestamp with time zone,
  "ordered_at" timestamp with time zone,
  "received_at" timestamp with time zone,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── purchase_order_items ────────────────────────────────────
CREATE TABLE IF NOT EXISTS "purchase_order_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "po_id" uuid NOT NULL REFERENCES "purchase_orders"("id") ON DELETE CASCADE,
  "variant_id" uuid REFERENCES "variants"("id") ON DELETE SET NULL,
  "sku" text,
  "quantity" integer NOT NULL,
  "unit_cost" numeric(12, 4),
  "quantity_received" integer DEFAULT 0 NOT NULL
);

-- ════════════════════════════════════════════════════════════
-- 5. Financieel
-- ════════════════════════════════════════════════════════════

-- ─── vat_rates ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "vat_rates" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "country" text NOT NULL,
  "tax_class" text NOT NULL,
  "rate" numeric(5, 2) NOT NULL,
  "label" text,
  "valid_from" date DEFAULT CURRENT_DATE NOT NULL,
  CONSTRAINT "vat_rates_country_class_from_unique" UNIQUE ("country", "tax_class", "valid_from")
);

-- ─── ledger_entries ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "ledger_entries" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid REFERENCES "shops"("id") ON DELETE SET NULL,
  "order_id" uuid REFERENCES "orders"("id") ON DELETE SET NULL,
  "entry_date" date NOT NULL,
  "account" text NOT NULL,
  "debit" numeric(12, 4) DEFAULT '0' NOT NULL,
  "credit" numeric(12, 4) DEFAULT '0' NOT NULL,
  "currency" text DEFAULT 'EUR' NOT NULL,
  "vat_rate" numeric(5, 2),
  "vat_country" text,
  "channel" text,
  "description" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE INDEX IF NOT EXISTS "ledger_entries_shop_date_idx"
  ON "ledger_entries" ("shop_id", "entry_date");

-- ─── invoices ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "invoices" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid NOT NULL REFERENCES "shops"("id") ON DELETE RESTRICT,
  "order_id" uuid REFERENCES "orders"("id") ON DELETE SET NULL,
  "invoice_number" text NOT NULL,
  "type" text DEFAULT 'sales' NOT NULL,
  "customer" jsonb,
  "lines" jsonb DEFAULT '[]' NOT NULL,
  "subtotal" numeric(12, 4),
  "vat_total" numeric(12, 4),
  "total" numeric(12, 4),
  "status" text DEFAULT 'issued' NOT NULL,
  "ubl_xml" text,
  "issued_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "invoices_shop_invoice_number_unique" UNIQUE ("shop_id", "invoice_number")
);

-- ─── payouts ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "payouts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "channel" text,
  "amount" numeric(12, 4),
  "period" text,
  "reference" text,
  "received_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── accounting_exports ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS "accounting_exports" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "type" text,
  "period" text,
  "status" text DEFAULT 'pending' NOT NULL,
  "file_path" text,
  "meta" jsonb DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ════════════════════════════════════════════════════════════
-- 6. Channels
-- ════════════════════════════════════════════════════════════

-- ─── channels ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "channels" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "type" text NOT NULL,
  "name" text NOT NULL,
  "status" text DEFAULT 'disconnected' NOT NULL,
  "credentials" jsonb,
  "config" jsonb DEFAULT '{}' NOT NULL,
  "last_sync_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ─── channel_products ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "channel_products" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "channel_id" uuid NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "product_id" uuid NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "variant_id" uuid REFERENCES "variants"("id") ON DELETE SET NULL,
  "external_id" text,
  "status" text DEFAULT 'pending' NOT NULL,
  "price_override" numeric(12, 4),
  "last_synced_at" timestamp with time zone,
  CONSTRAINT "channel_products_channel_variant_unique" UNIQUE ("channel_id", "variant_id")
);

-- ─── channel_orders ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "channel_orders" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "channel_id" uuid NOT NULL REFERENCES "channels"("id") ON DELETE CASCADE,
  "external_order_id" text,
  "order_id" uuid REFERENCES "orders"("id") ON DELETE SET NULL,
  "raw" jsonb,
  "imported_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "channel_orders_channel_external_unique" UNIQUE ("channel_id", "external_order_id")
);

-- ════════════════════════════════════════════════════════════
-- updated_at-triggers (gebruiken bestaande set_updated_at() uit 0000)
-- Alleen tabellen met een updated_at-kolom.
-- ════════════════════════════════════════════════════════════

CREATE TRIGGER shops_updated_at
  BEFORE UPDATE ON "shops"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER cms_pages_updated_at
  BEFORE UPDATE ON "cms_pages"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER cms_blocks_updated_at
  BEFORE UPDATE ON "cms_blocks"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER cms_menus_updated_at
  BEFORE UPDATE ON "cms_menus"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER blog_posts_updated_at
  BEFORE UPDATE ON "blog_posts"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER customers_updated_at
  BEFORE UPDATE ON "customers"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER orders_updated_at
  BEFORE UPDATE ON "orders"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER carts_updated_at
  BEFORE UPDATE ON "carts"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER returns_updated_at
  BEFORE UPDATE ON "returns"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER suppliers_updated_at
  BEFORE UPDATE ON "suppliers"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER purchase_orders_updated_at
  BEFORE UPDATE ON "purchase_orders"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER channels_updated_at
  BEFORE UPDATE ON "channels"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
