-- ============================================================
-- Migration 0002 — Wave A2: outbound webhooks
-- Generated by Atlas (handmatig conform Drizzle-conventies).
--
-- LET OP: drizzle-kit 0.28.1 kan de ESM `.js`-imports in schema/index.ts niet
-- via zijn CJS-loader resolven, dus `db:generate` faalt (zoals bij 0000/0001).
-- Daarom is deze migratie handgeschreven — PUUR ADDITIEF. 0000/0001 + bestaande
-- tabellen worden NOOIT aangeraakt. `set_updated_at()` bestaat al uit 0000.
--
-- 1 nieuwe tabel: webhooks. Geen FK's (shop_id is bewust nullable/los —
-- null = globale webhook).
-- ============================================================

-- ─── webhooks ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "webhooks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "shop_id" uuid,
  "event" text NOT NULL,
  "url" text NOT NULL,
  "secret" text,
  "scope" text NOT NULL,
  "active" boolean DEFAULT true NOT NULL,
  "last_fired_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- ════════════════════════════════════════════════════════════
-- updated_at-trigger (gebruikt bestaande set_updated_at() uit 0000)
-- ════════════════════════════════════════════════════════════

CREATE TRIGGER webhooks_updated_at
  BEFORE UPDATE ON "webhooks"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
