-- ============================================================
-- Migration 0003 — Wave-H A3: per-shop PUBLISHABLE storefront-token
-- Generated by Atlas (handmatig conform Drizzle-conventies).
--
-- LET OP: drizzle-kit 0.28.1 kan de ESM `.js`-imports in schema/index.ts niet
-- via zijn CJS-loader resolven, dus `db:generate` faalt (zoals bij 0000/0001/0002).
-- Daarom is deze migratie handgeschreven — PUUR ADDITIEF. Bestaande tabellen +
-- kolommen worden NOOIT aangeraakt.
--
-- 1 nieuwe kolom op `shops`: storefront_token_hash. Bevat ALLEEN een sha256-hash
-- (hex) van het publishable-token (format 'wcrm_pk_<32+ url-safe random bytes>').
-- De raw waarde wordt NOOIT opgeslagen — alleen de hash, zodat een DB-lek geen
-- bruikbare tokens prijsgeeft. Nullable: een shop hoeft (nog) geen token te hebben.
--
-- De storefront-resolver matcht inkomende X-Storefront-Token tegen deze hash.
-- Index op de hash zodat token-lookups op de publieke storefront-API snel zijn.
-- ============================================================

-- ─── shops.storefront_token_hash ─────────────────────────────
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "storefront_token_hash" text;

-- Snelle lookup vanuit de storefront-resolver (sha256(token) → shop).
-- Partial index: alleen rijen die daadwerkelijk een token hebben.
CREATE INDEX IF NOT EXISTS "shops_storefront_token_hash_idx"
  ON "shops" ("storefront_token_hash")
  WHERE "storefront_token_hash" IS NOT NULL;
