-- ============================================================
-- Migration 0004 — Wave-H A4: pluggable per-shop payment provider (Mollie)
-- Generated by Atlas (handmatig conform Drizzle-conventies).
--
-- LET OP: drizzle-kit 0.28.1 kan de ESM `.js`-imports in schema/index.ts niet
-- via zijn CJS-loader resolven, dus `db:generate` faalt (zoals bij 0000/0001/
-- 0002/0003). Daarom is deze migratie handgeschreven — PUUR ADDITIEF. Bestaande
-- tabellen + kolommen worden NOOIT aangeraakt.
--
-- 2 nieuwe kolommen op `shops`:
--   - payment_provider     text  — geconfigureerde PSP-key ('mollie'). NULL = geen
--                                   provider → checkout houdt het mock-paid-pad.
--   - payment_credentials  jsonb — encrypted `{ enc }`-blob (channel-crypto
--                                   AES-256-GCM) met `{ apiKey: 'test_…'|'live_…' }`.
--                                   NOOIT raw teruggegeven door de API.
--
-- Niet-breaking: beide nullable, geen default, geen FK. Shops zonder deze velden
-- gedragen zich exact als voorheen (mock-paid + ledger).
-- ============================================================

-- ─── shops.payment_provider ──────────────────────────────────
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "payment_provider" text;

-- ─── shops.payment_credentials (encrypted blob) ──────────────
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "payment_credentials" jsonb;
