-- ============================================================
-- Migration 0005 — Shipping / carriers (koppel-klaar)
-- Generated by Atlas (handmatig conform Drizzle-conventies).
--
-- PUUR ADDITIEF — bestaande tabellen/kolommen worden NOOIT aangeraakt.
-- 2 nieuwe tabellen: shipping_carriers + shipments.
-- Hergebruikt set_updated_at() (bestaat al sinds 0000).
-- ============================================================

-- ─── shipping_carriers ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS "shipping_carriers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "status" text DEFAULT 'disconnected' NOT NULL,
  "credentials" jsonb,
  "config" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "last_test_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "shipping_carriers_code_unique" UNIQUE ("code")
);

-- ─── shipments ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "shipments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "order_id" uuid NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "carrier_id" uuid REFERENCES "shipping_carriers"("id") ON DELETE SET NULL,
  "carrier_code" text,
  "tracking_code" text,
  "tracking_url" text,
  "label_url" text,
  "status" text DEFAULT 'pending' NOT NULL,
  "weight_grams" integer,
  "raw" jsonb,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "shipments_order_id_idx"
  ON "shipments" ("order_id");

-- ─── updated_at-triggers (bestaande set_updated_at() uit 0000) ──
DROP TRIGGER IF EXISTS shipping_carriers_updated_at ON "shipping_carriers";
CREATE TRIGGER shipping_carriers_updated_at
  BEFORE UPDATE ON "shipping_carriers"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS shipments_updated_at ON "shipments";
CREATE TRIGGER shipments_updated_at
  BEFORE UPDATE ON "shipments"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
