/**
 * Download-helpers voor mock-PDF/HTML/CSV/ZIP-export-flows.
 * Pure-frontend; gebruik Blob + objectURL.
 */
import { formatMoney, formatDate } from './format';

export function downloadBlob(filename: string, content: string | Blob, type = 'application/octet-stream') {
  const blob = content instanceof Blob ? content : new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

interface InvoiceLike {
  number: string;
  customerName: string;
  shippingAddress: { name: string; street: string; zip: string; city: string; country: string };
  lines: Array<{ title: string; variantSku: string; qty: number; unitPrice: number; lineTotal: number; vatRate: number }>;
  subtotalExclVat: number;
  vatAmount: number;
  shippingAmount: number;
  discountAmount: number;
  total: number;
  vatScheme: string;
  invoiceNumber?: string;
  createdAt: string;
}

export function buildInvoiceHtml(o: InvoiceLike): string {
  const linesHtml = o.lines.map((l) => `
    <tr>
      <td style="padding:8px;border-bottom:1px solid #eee">
        <div style="font-weight:600">${escapeHtml(l.title)}</div>
        <div style="font-size:11px;color:#888">${escapeHtml(l.variantSku)} • BTW ${l.vatRate}%</div>
      </td>
      <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${l.qty}×</td>
      <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${formatMoney(l.unitPrice)}</td>
      <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;font-weight:600">${formatMoney(l.lineTotal)}</td>
    </tr>`).join('');

  return `<!doctype html>
<html lang="nl">
<head>
<meta charset="utf-8">
<title>Factuur ${escapeHtml(o.invoiceNumber ?? o.number)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; max-width: 800px; margin: 40px auto; padding: 20px; }
  header { display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 24px; border-bottom: 2px solid #ff9f43; margin-bottom: 24px; }
  h1 { margin: 0 0 4px; font-size: 28px; color: #0d0f12; }
  .muted { color: #888; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
  th { text-align: left; padding: 8px; background: #f6f6f6; font-size: 12px; text-transform: uppercase; }
  .totals { margin-top: 20px; width: 50%; margin-left: auto; }
  .totals .row { display: flex; justify-content: space-between; padding: 4px 0; }
  .totals .total { padding-top: 10px; border-top: 2px solid #1a1a1a; font-size: 18px; font-weight: 700; }
  footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 11px; color: #888; }
</style>
</head>
<body>
<header>
  <div>
    <h1>Factuur</h1>
    <div class="muted">Webshop-CRM • Demo BV</div>
    <div class="muted">Hoofdstraat 1 • 1011 AA Amsterdam</div>
    <div class="muted">BTW: NL123456789B01 • KvK: 12345678</div>
  </div>
  <div style="text-align:right">
    <div style="font-size:18px;font-weight:600">${escapeHtml(o.invoiceNumber ?? o.number)}</div>
    <div class="muted">Order: ${escapeHtml(o.number)}</div>
    <div class="muted">Datum: ${escapeHtml(formatDate(o.createdAt))}</div>
    <div class="muted" style="margin-top:8px">Scheme: ${escapeHtml(o.vatScheme)}</div>
  </div>
</header>

<section style="display:flex;gap:24px;margin-bottom:24px">
  <div style="flex:1">
    <div style="font-size:11px;text-transform:uppercase;color:#888;font-weight:600;letter-spacing:0.04em;margin-bottom:6px">Klant</div>
    <div style="font-weight:600">${escapeHtml(o.customerName)}</div>
    <div class="muted">${escapeHtml(o.shippingAddress.street)}</div>
    <div class="muted">${escapeHtml(o.shippingAddress.zip)} ${escapeHtml(o.shippingAddress.city)}</div>
    <div class="muted">${escapeHtml(o.shippingAddress.country)}</div>
  </div>
</section>

<table>
  <thead>
    <tr>
      <th>Omschrijving</th>
      <th style="text-align:right">Aantal</th>
      <th style="text-align:right">Stuksprijs</th>
      <th style="text-align:right">Totaal</th>
    </tr>
  </thead>
  <tbody>
    ${linesHtml}
  </tbody>
</table>

<div class="totals">
  <div class="row"><span>Subtotaal (excl)</span><span>${formatMoney(o.subtotalExclVat)}</span></div>
  <div class="row"><span>BTW</span><span>${formatMoney(o.vatAmount)}</span></div>
  <div class="row"><span>Verzending</span><span>${formatMoney(o.shippingAmount)}</span></div>
  ${o.discountAmount > 0 ? `<div class="row"><span>Korting</span><span>− ${formatMoney(o.discountAmount)}</span></div>` : ''}
  <div class="row total"><span>Totaal</span><span>${formatMoney(o.total)}</span></div>
</div>

<footer>
  Generated by Webshop-CRM Admin (mock-mode). Geen rechtsgeldige factuur.
</footer>
</body>
</html>`;
}

interface PackingSlipLike {
  number: string;
  customerName: string;
  shippingAddress: { name: string; street: string; zip: string; city: string; country: string };
  shippingMethod: string;
  trackingNumber?: string;
  lines: Array<{ title: string; variantSku: string; qty: number }>;
  itemsCount: number;
}

export function buildPackingSlipHtml(o: PackingSlipLike): string {
  const linesHtml = o.lines.map((l) => `
    <tr>
      <td style="padding:8px;border-bottom:1px solid #eee">
        <div style="font-weight:600">${escapeHtml(l.title)}</div>
        <div style="font-size:11px;font-family:monospace;color:#888">${escapeHtml(l.variantSku)}</div>
      </td>
      <td style="padding:8px;border-bottom:1px solid #eee;text-align:right;font-size:18px;font-weight:700">${l.qty}×</td>
      <td style="padding:8px;border-bottom:1px solid #eee;text-align:center;width:60px">
        <div style="width:18px;height:18px;border:2px solid #1a1a1a;border-radius:3px;margin:0 auto"></div>
      </td>
    </tr>`).join('');
  return `<!doctype html>
<html lang="nl">
<head>
<meta charset="utf-8">
<title>Pak-bon ${escapeHtml(o.number)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
  header { padding-bottom: 16px; border-bottom: 2px solid #1a1a1a; margin-bottom: 16px; }
  h1 { margin: 0; font-size: 26px; }
  .muted { color: #888; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { text-align: left; padding: 8px; background: #f6f6f6; font-size: 12px; }
</style>
</head>
<body>
<header>
  <h1>Pak-bon — ${escapeHtml(o.number)}</h1>
  <div class="muted">Aantal items: ${o.itemsCount} • ${escapeHtml(o.shippingMethod)}${o.trackingNumber ? ` • Tracking: ${escapeHtml(o.trackingNumber)}` : ''}</div>
</header>
<section style="margin-bottom:16px">
  <div style="font-weight:600">${escapeHtml(o.customerName)}</div>
  <div class="muted">${escapeHtml(o.shippingAddress.street)}</div>
  <div class="muted">${escapeHtml(o.shippingAddress.zip)} ${escapeHtml(o.shippingAddress.city)}, ${escapeHtml(o.shippingAddress.country)}</div>
</section>
<table>
  <thead>
    <tr>
      <th>Item</th>
      <th style="text-align:right">Aantal</th>
      <th style="text-align:center">Check</th>
    </tr>
  </thead>
  <tbody>${linesHtml}</tbody>
</table>
<div style="margin-top:30px;padding:12px;background:#fffae6;border-left:3px solid #ff9f43;font-size:12px">
  Vergeet niet: factuur in de doos, label op de doos, doos in de bak.
</div>
</body>
</html>`;
}

/** Build a tiny dummy-PDF (text-only, opens in PDF readers). */
export function buildDummyPdf(title: string, body: string): Blob {
  // Minimaal valid PDF — Hello world style
  const escape = (s: string) => s.replace(/[()\\]/g, (m) => '\\' + m);
  const text = `${escape(title)}\n\n${escape(body)}`;
  const stream = `BT /F1 12 Tf 50 750 Td (${text.replace(/\n/g, ') Tj 0 -16 Td (')}) Tj ET`;
  const bytes =
`%PDF-1.4
1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj
2 0 obj << /Type /Pages /Count 1 /Kids [3 0 R] >> endobj
3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj
4 0 obj << /Length ${stream.length} >> stream
${stream}
endstream endobj
5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj
xref
0 6
0000000000 65535 f
0000000010 00000 n
0000000053 00000 n
0000000100 00000 n
0000000200 00000 n
0000000300 00000 n
trailer << /Size 6 /Root 1 0 R >>
startxref
400
%%EOF`;
  return new Blob([bytes], { type: 'application/pdf' });
}

/** Build a tiny dummy-CSV. */
export function buildCsv(rows: Array<Record<string, string | number>>, columns?: string[]): string {
  if (rows.length === 0) return '';
  const cols = columns ?? Object.keys(rows[0]!);
  const lines = [cols.join(',')];
  for (const r of rows) {
    lines.push(cols.map((c) => csvEscape(String(r[c] ?? ''))).join(','));
  }
  return lines.join('\n');
}

function csvEscape(s: string): string {
  if (s.includes('"') || s.includes(',') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Fake-OSS-CSV for accounting export. */
export function buildOssCsv(period: string): string {
  const rows = [
    { country: 'DE', rate: 19, base: 6420, vat: 1219.8 },
    { country: 'FR', rate: 20, base: 3180, vat: 636 },
    { country: 'BE', rate: 21, base: 1820, vat: 382.2 },
  ];
  const header = `# OSS Quarterly Declaration — ${period}\n# Generated by Webshop-CRM (mock)\n`;
  return header + buildCsv(rows.map((r) => ({
    period,
    country: r.country,
    vat_rate: r.rate,
    taxable_base: r.base,
    vat_amount: r.vat,
  })), ['period', 'country', 'vat_rate', 'taxable_base', 'vat_amount']);
}
